export const PROFILE_PICTURES = [

  { id: 'lucia', url: '/images/avatars/ava-lucia.png', label: 'Lucia' },
  { id: 'jason', url: '/images/avatars/ava-jason.png', label: 'Jason' },
  { id: 'tommy', url: '/images/avatars/ava-tommy.png', label: 'Tommy Vercetti' },
  { id: 'franklin', url: '/images/avatars/ava-franklin.png', label: 'Franklin Clinton' },
  { id: 'michael', url: '/images/avatars/ava-michael.png', label: 'Michael De Santa' },
  { id: 'trevor', url: '/images/avatars/ava-trevor.png', label: 'Trevor Phillips' },
  { id: 'chop', url: '/images/avatars/ava-chop.png', label: 'Chop' },
  { id: 'niko', url: '/images/avatars/ava-niko.png', label: 'Niko Bellick' },
  { id: 'cj', url: '/images/avatars/ava-cj.png', label: 'Carl Johnson' },
  { id: 'bigsmoke', url: '/images/avatars/ava-bigsmoke.png', label: 'Big Smoke' },
  { id: 'ryder', url: '/images/avatars/ava-ryder.png', label: 'Ryder' },
  { id: 'claude', url: '/images/avatars/ava-claude.png', label: 'Claude' },
  { id: 'ava1', url: '/images/avatars/ava1.png', label: 'Avatar 1' },
  { id: 'ava2', url: '/images/avatars/ava2.png', label: 'Avatar 2' },
  { id: 'ava3', url: '/images/avatars/ava3.png', label: 'Avatar 3' },
  { id: 'ava4', url: '/images/avatars/ava4.png', label: 'Avatar 4' },
  { id: 'ava5', url: '/images/avatars/ava5.png', label: 'Avatar 5' },
  { id: 'ava6', url: '/images/avatars/ava6.png', label: 'Avatar 6' },
  { id: 'ava7', url: '/images/avatars/ava7.png', label: 'Avatar 7' },
  { id: 'ava8', url: '/images/avatars/ava8.png', label: 'Avatar 8' },
  { id: 'ava9', url: '/images/avatars/ava9.png', label: 'Avatar 9' },
  { id: 'ava10', url: '/images/avatars/ava10.png', label: 'Avatar 10' },
  { id: 'ava11', url: '/images/avatars/ava11.png', label: 'Avatar 11' },
  { id: 'ava12', url: '/images/avatars/ava12.png', label: 'Avatar 12' },
  { id: 'ava13', url: '/images/avatars/ava13.png', label: 'Avatar 13' },
  { id: 'ava14', url: '/images/avatars/ava14.png', label: 'Avatar 14' },
  { id: 'ava15', url: '/images/avatars/ava15.png', label: 'Avatar 15' },
  { id: 'ava16', url: '/images/avatars/ava16.png', label: 'Avatar 16' },
  { id: 'ava17', url: '/images/avatars/ava17.png', label: 'Avatar 17' },
  { id: 'ava18', url: '/images/avatars/ava18.png', label: 'Avatar 18' },
  { id: 'ava19', url: '/images/avatars/ava19.png', label: 'Avatar 19' },
  { id: 'ava20', url: '/images/avatars/ava20.png', label: 'Avatar 20' },
  { id: 'ava21', url: '/images/avatars/ava21.png', label: 'Avatar 21' },
  { id: 'ava22', url: '/images/avatars/ava22.png', label: 'Avatar 22' },
  { id: 'ava23', url: '/images/avatars/ava23.png', label: 'Avatar 23' },
  { id: 'ava24', url: '/images/avatars/ava24.png', label: 'Avatar 24' },
  { id: 'ava25', url: '/images/avatars/ava25.png', label: 'Avatar 25' },
  { id: 'ava26', url: '/images/avatars/ava26.png', label: 'Avatar 26' },
  { id: 'ava27', url: '/images/avatars/ava27.png', label: 'Avatar 27' },
  { id: 'ava28', url: '/images/avatars/ava28.png', label: 'Avatar 28' },
  { id: 'ava29', url: '/images/avatars/ava29.png', label: 'Avatar 29' },
  { id: 'ava30', url: '/images/avatars/ava30.png', label: 'Avatar 30' },
  { id: 'ava31', url: '/images/avatars/ava31.png', label: 'Avatar 31' },
  { id: 'ava32', url: '/images/avatars/ava32.png', label: 'Avatar 32' },
  { id: 'ava33', url: '/images/avatars/ava33.png', label: 'Avatar 33' },
  { id: 'ava34', url: '/images/avatars/ava34.png', label: 'Avatar 34' },
  { id: 'ava35', url: '/images/avatars/ava35.png', label: 'Avatar 35' },
  { id: 'ava36', url: '/images/avatars/ava36.png', label: 'Avatar 36' },
  { id: 'ava37', url: '/images/avatars/ava37.png', label: 'Avatar 37' },
  { id: 'ava38', url: '/images/avatars/ava38.png', label: 'Avatar 38' },
  { id: 'ava39', url: '/images/avatars/ava39.png', label: 'Avatar 39' },
  { id: 'ava40', url: '/images/avatars/ava40.png', label: 'Avatar 40' },
  { id: 'ava41', url: '/images/avatars/ava41.png', label: 'Avatar 41' },
  { id: 'ava42', url: '/images/avatars/ava42.png', label: 'Avatar 42' },
  { id: 'ava43', url: '/images/avatars/ava43.png', label: 'Avatar 43' },
  { id: 'ava44', url: '/images/avatars/ava44.png', label: 'Avatar 44' },
  { id: 'ava45', url: '/images/avatars/ava45.png', label: 'Avatar 45' },
  { id: 'ava46', url: '/images/avatars/ava46.png', label: 'Avatar 46' },
  { id: 'ava47', url: '/images/avatars/ava47.png', label: 'Avatar 47' },
  { id: 'ava48', url: '/images/avatars/ava48.png', label: 'Avatar 48' },
  { id: 'ava49', url: '/images/avatars/ava49.png', label: 'Avatar 49' },
  { id: 'ava50', url: '/images/avatars/ava50.png', label: 'Avatar 50' },
  { id: 'ava51', url: '/images/avatars/ava51.png', label: 'Avatar 51' },
  { id: 'ava52', url: '/images/avatars/ava52.png', label: 'Avatar 52' },
  { id: 'ava53', url: '/images/avatars/ava53.png', label: 'Avatar 53' },
  { id: 'ava54', url: '/images/avatars/ava54.png', label: 'Avatar 54' },
  { id: 'ava55', url: '/images/avatars/ava55.png', label: 'Avatar 55' },
  { id: 'ava56', url: '/images/avatars/ava56.png', label: 'Avatar 56' },

] as const;

export const getRandomProfilePicture = () => {
  const randomIndex = Math.floor(Math.random() * PROFILE_PICTURES.length);
  return PROFILE_PICTURES[randomIndex].url;
}; 